apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: run-service
  name: run-service
  namespace: user-ns-boydj
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: run-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: run-service
    spec:
      containers:
      - image: public.ecr.aws/o6u7e2l7/bsidesnova2022:boydj-workshop-application-ea5b4ac24be8253aade399084413a4cc8770660a
        imagePullPolicy: Always
        name: pause
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
